dist: xenial
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
services:
  - redis
  - mongodb
cache: npm
install:
    - "cd api && npm install"
script:
    - "npm test"
after_success:
    - "npm run coverage"
