FROM keymetrics/pm2:latest-alpine

RUN npm install pm2 -g

ENV NODE_ENV=production

ENV PRODUCT_URL=https://getstream.io/winds
ENV PRODUCT_NAME=Winds
ENV PRODUCT_AUTHOR=GetStream.io

ENV JWT_SECRET=YOUR_RANDOM_JWT_SECRET

ENV DATABASE_URI=YOUR_MONGODB_URI
ENV CACHE_URI=YOUR_REDIS_CACHE_URI

ENV MERCURY_KEY=YOUR_MERCURY_KEY

ENV ALGOLIA_APP_ID=YOUR_ALGOLIA_APP_ID
ENV ALGOLIA_WRITE_KEY=YOUR_ALGOLIA_WRITE_KEY
ENV ALGOLIA_INDEX=YOUR_ALGOLIA_INDEX

ENV EMAIL_SENDER_DEFAULT_NAME=YOUR_NAME
ENV EMAIL_SENDER_DEFAULT_EMAIL=YOUR_EMAIL
ENV EMAIL_SENDER_SUPPORT_NAME=Winds
ENV EMAIL_SENDER_SUPPORT_EMAIL=YOUR_SUPPORT_EMAIL

ENV EMAIL_SENDGRID_SECRET=YOUR_SENDGRID_SECRET

ENV STREAM_APP_ID=YOUR_STREAM_APP_ID
ENV STREAM_API_KEY=YOUR_STREAM_API_KEY
ENV STREAM_API_SECRET=YOUR_STREAM_API_SECRET
ENV STREAM_API_BASE_URL=https://windspersonalization.getstream.io/personalization/v1.0

ENV SENTRY_DSN=YOUR_SENTRY_DSN

EXPOSE 8080

CMD ["pm2-runtime", "process_prod.json"]
