name: Test
on: push

defaults:
  run:
    working-directory: api

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test